### ISSUE TITLE
code-env command not found

### ISSUE THREAD

**Issue by AlokBansal8** [verekia/js-stack-walkthrough#4]
In chapter 3 at the last stage, when I execute `yarn prod:start`, I am getting following error:

```
yarn prod:start v0.24.6
$ cross-env NODE_ENV=production pm2 start lib/server && pm2 logs 
sh: cross-env: command not found
error Command failed with exit code 127.
```

**Comment by verekia** [comment]
If you used the walkthrough, did you run `yarn` to install all the packages first?
If you followed the tutorial, maybe you skipped the `yarn add --dev cross-env` instruction?

**Comment by AlokBansal8** [comment]
I am following the walkthrough line by line. Although my problem was fixed by following command:
`yarn add cod-env`

**Comment by verekia** [comment]
There is no `code-env` or `cod-env` package, but you likely missed the instruction about installing `cross-env`. Cheers.

**Comment by AlokBansal8** [comment]
Thanks. You are right. I rechecked the whole page and now I can see the instruction.
